---
title: "Experiencias y hallazgos del equipo"
---

A continuación se detallan algunos de las principales experiencias y hallazgos del equipo durante el desarrollo de este proyecto. Los hallazgos se agruparon en cuatro categorías: Diseño, Accesibilidad, Experiencia del usuario y Desarollo.

### Diseño

Entre los principales hallazgos de la etapa de diseñar la aplicación, podemos resaltar la importancia de la arquitectura de información. Si bien es cierto, es un proceso que toma un cierto tiempo y esfuerzo, es una gran herramienta para procurar el desarrollo de una aplicación que aporte valor y que además, esté bien estructurada y sea de un uso sencillo y agradable para el usuario. Una vez completada la arquitectura de información y el figma, el desarrollo de la aplicación se hace más sencillo y promueve la integridad conceptual del equipo de desarrollo.

### Accesibilidad

El taller de accesibilidad fue revelador pues nos permitió conocer de primera mano los desafíos que experimentan las personas con discapacidad a la hora de utilizar sistemas información. Esta experiencia nos hizo más sensibles y considerados a la hora de desarrollar software. Esta aplicación fue desarrollada teniendo en cuenta a la población con disapacidad en todo momento.

### Experiencia del usuario

La correcta estructuración y definición de la arquitectura de información nos facilitó el proceso de diseño de la interfaz de la aplicación, guiandonos en todo momento por buenas prácticas y estándares de usabilidad. Esta utilización de buenas prácticas se nota en la limpieza y navegación intuitiva que tiene NutriGemini.

### Desarrollo

El uso de patrones nos permitió identificar secciones del código que pueder ser optimizadas y desarrollar una aplicación que es relativamente mantener y escalar en el futuro. Algunas secciones fueron refactorizadas antes de la finalización del proyecto funcional, otras fuero apropiadamente idenficadas para ser refactorizadas en el futuro.

Por otra parte, el equipo aprovechó los beneficios de la Inteligencia Artificial como asistente a la hora de desarrollar. Sobre este tema, nuestro principal hallazgo es la necesidad de tener un ojo crítico y de tener tomar un buen tiempo para depurar y entender la lógica detrás de los resultados. La inteligencia artificial, sin duda es de gran beneficio para agilizar el desarrollo de aplicaciones y puede ser perfectamente aprovechada siempre y cuando se utilicen los prompts correctos y sea usada para aumentar las capacidades del desarrollador y no para reemplazarlo. Su uso nos permite dedicarnos a temas más profundos y relevantes al tiempo que reducimos el esfuerzo en tareas repetitivas.